version: '3'
services:

  sample-application:
    image: akshatarora/sit737:task5
    build: 
      context: ./
      dockerfile: Dockerfile-dev
    container_name: task5
    ports:
      - "8080:3000"
    restart: "no"
    healthcheck:
      test: curl --fail http://localhost:8080/add?n1=3&n2=5 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

